In [13]:
# Importing all necessary libararies
import pandas as pd
import numpy as np

df = pd.read_csv("../data/processed/ad_click_clean.csv")

df.head()

     id full_name   age      gender device_type ad_position time_of_day  click
0   670   User670  22.0     Unknown     Desktop         Top   Afternoon      1
1  3044  User3044  39.5        Male     Desktop         Top     Unknown      1
2  5912  User5912  41.0  Non-Binary     Unknown        Side       Night      1
3  5418  User5418  34.0        Male     Unknown     Unknown     Evening      1
4  9452  User9452  39.0  Non-Binary     Unknown     Unknown     Morning      0

In [14]:
# Here we identify feature types that we have in our dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           10000 non-null  int64
 1   full_name    10000 non-null  str
 2   age          10000 non-null  float64
 3   gender       10000 non-null  str
 4   device_type  10000 non-null  str
 5   ad_position  10000 non-null  str
 6   time_of_day  10000 non-null  str
 7   click        10000 non-null  int64
dtypes: float64(1), int64(2), str(5)
memory usage: 625.1 KB

In [15]:
#In this cell we drop non-predictive columns 
df.drop(columns=["id", "full_name"], inplace=True)

In [16]:
# Encoding target variables
df["click"].unique()

array([1, 0])

In [17]:
#One Hot Encoding 
df_encoded = pd.get_dummies(
    df,
    columns=["gender", "device_type", "ad_position", "time_of_day"],
    drop_first=True
)



df_encoded = df_encoded.astype({
    col: 'int'
    for col in df_encoded.columns
    if df_encoded[col].dtype == 'bool'
})

df_encoded.head()

,age,click,gender_Male,gender_Non-Binary,gender_Unknown,device_type_Mobile,device_type_Tablet,device_type_Unknown,ad_position_Side,ad_position_Top,ad_position_Unknown,time_of_day_Evening,time_of_day_Morning,time_of_day_Night,time_of_day_Unknown
0,22.0,1,0,0,1,0,0,0,0,1,0,0,0,0,0
1,39.5,1,1,0,0,0,0,0,0,1,0,0,0,0,1
2,41.0,1,0,1,0,0,0,1,1,0,0,0,0,1,0
3,34.0,1,1,0,0,0,0,1,0,0,1,1,0,0,0
4,39.0,0,0,1,0,0,0,1,0,0,1,0,1,0,0

In [18]:
df_encoded.drop(columns=["id", "full_name"], inplace=True, errors="ignore")

In [19]:
# checking final dataset
df_encoded.shape

(10000, 15)

In [20]:
# checking the final dataset
df_encoded.head()

,age,click,gender_Male,gender_Non-Binary,gender_Unknown,device_type_Mobile,device_type_Tablet,device_type_Unknown,ad_position_Side,ad_position_Top,ad_position_Unknown,time_of_day_Evening,time_of_day_Morning,time_of_day_Night,time_of_day_Unknown
0,22.0,1,0,0,1,0,0,0,0,1,0,0,0,0,0
1,39.5,1,1,0,0,0,0,0,0,1,0,0,0,0,1
2,41.0,1,0,1,0,0,0,1,1,0,0,0,0,1,0
3,34.0,1,1,0,0,0,0,1,0,0,1,1,0,0,0
4,39.0,0,0,1,0,0,0,1,0,0,1,0,1,0,0

In [21]:
# Separating Features and Targets
X = df_encoded.drop("click", axis=1)
y = df_encoded["click"]

In [22]:
# Verifying shapes
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (10000, 14)
y shape: (10000,)

In [23]:
X.head()

,age,gender_Male,gender_Non-Binary,gender_Unknown,device_type_Mobile,device_type_Tablet,device_type_Unknown,ad_position_Side,ad_position_Top,ad_position_Unknown,time_of_day_Evening,time_of_day_Morning,time_of_day_Night,time_of_day_Unknown
0,22.0,0,0,1,0,0,0,0,1,0,0,0,0,0
1,39.5,1,0,0,0,0,0,0,1,0,0,0,0,1
2,41.0,0,1,0,0,0,1,1,0,0,0,0,1,0
3,34.0,1,0,0,0,0,1,0,0,1,1,0,0,0
4,39.0,0,1,0,0,0,1,0,0,1,0,1,0,0

In [24]:
#💾 STEP 11: SAVE PROCESSED DATA
df.to_csv("../data/processed/ad_click_clean_featured_engineered.csv", index=False)